---
# @see https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb
extends: '@ia/eslint-config-ia'

globals:
  __DEV__: true

rules:
  # @see http://eslint.org/docs/rules/semi
  semi: 0
  # @see http://eslint.org/docs/rules/no-new
  no-new: 0
  no-param-reassign: 0
  import/extensions: 0
  comma-dangle: 0
  arrow-parens: 0
  no-plusplus: 0
  space-before-function-paren: 0
  no-restricted-syntax: 0
  no-prototype-builtins: 0

# settings for eslint-plugin-import work with webpack resolve
# @see https://github.com/benmosher/eslint-plugin-import
settings:
  import/resolver:
    webpack:
      config: 'webpack/client.development.config.js'